Pages/UserFolder/DeleteAll.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using UsersProject.ApiSevices;
using UsersProject.Middleware;
using UsersProject.Models;

namespace UsersProject.Pages.UserFolder
{
    public class DeleteAllModel : PageModel
    {
        private readonly WebApis _webApis;
        public bool isDeleteAll { get; set; }

        public DeleteAllModel(WebApis webApis)
        {
            _webApis = webApis;
        }
        public void OnGet()
        {
            TempData["isDeleteAll"] = false;
        }

        public async Task<ActionResult> OnPostConfirmAdminAsync(string password)
        {
            // Validate the password
            //bool isAdminValid = objUser.Admin_Validation(TempData["AdminNameForDelete"].ToString(), password);
            var validateUserRequest = new ValidateUserRequest
            {
                UserName = TempData["AdminNameForDelete"].ToString(),
                Password = password
            };

            var response = await _webApis.AdminVaidationApiAsync(validateUserRequest);

            if (response.IsSuccessStatusCode)
            {
                string responseContent = DecryptionHelper.DecryptString(await response.Content.ReadAsStringAsync());
                TempData["isDeleteAll"] = true; // Set TempData to indicate confirmation
            }
            else
            {
                TempData["isDeleteAll"] = false;
                TempData["isSuccess"] = false;
                TempData["SuccessMSG"] = "Wrong Password!!";
            }

            TempData.Keep("isDeleteAll");
            TempData.Keep("AdminNameForDelete");
            return Page();
        }
        public async Task<ActionResult> OnPostDeleteAll()
        {
            return Page();
            if (TempData["isDeleteAll"] as bool? == true)
            {
                if (Request.Cookies.TryGetValue("jwt_token", out var token))
                {
                    await _webApis.DeleteAllPersonsApiAsync(token);
                }
                else
                {
                    return Unauthorized();
                }
                //objUser.DeleteAllPersons();
                TempData["isDeleteAll"] = false; // Reset TempData after operation
                TempData["isSuccess"] = true;
                TempData["SuccessMSG"] = "All Data Deleted Successfully!!";
            }
            else
            {
                TempData["isDeleteAll"] = false; // Reset TempData after operation
                TempData["isSuccess"] = false;
                TempData["SuccessMSG"] = "Data Deletion Failed!!";

            }

            return RedirectToPage("./UserIndex");
        }
    }
}

Pages/UserFolder/DeleteUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using UsersProject.ApiSevices;
using UsersProject.Middleware;
using UsersProject.Models;

namespace UsersProject.Pages.UserFolder
{
    public class DeleteUserModel : PageModel
    {
        private readonly WebApis _webApis;

        [BindProperty]
        public UserPerson User { get; set; }

        public DeleteUserModel(WebApis webApis)
        {
            _webApis = webApis;
        }
        public async Task<ActionResult> OnGet(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            if (TempData["isUser"] != null && TempData["isUser"] as Boolean? == true && TempData["UserPassword"] != null)
            {
                TempData.Keep("isUser");
                TempData.Keep("UserPassword");
                if (Request.Cookies.TryGetValue("jwt_token", out var token))
                {
                    User = await _webApis.GetUserDataApiAsync(id, TempData["UserPassword"].ToString(), token);
                    TempData.Keep("UserPassword");
                }
                else
                {
                    return Unauthorized();
                }
                //User = objUser.GetUserData(id, TempData["UserPassword"].ToString());
            }
            else
            {
                if (Request.Cookies.TryGetValue("jwt_token", out var token))
                {
                    User = await _webApis.GetUserDataApiAsync(id, token: token);
                }
                else
                {
                    return Unauthorized();
                }
                //User = objUser.GetUserData(id);
            }
            TempData.Keep("UserPassword");

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<ActionResult> OnPost(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (Request.Cookies.TryGetValue("jwt_token", out var token))
            {
                var response = await _webApis.DeleteOnePersonApiAsync(id, token);
                if (response.IsSuccessStatusCode)
                {
                    string responseContent = DecryptionHelper.DecryptString(await response.Content.ReadAsStringAsync());
                    var result = JsonConvert.DeserializeObject<List<string>>(responseContent);
                    // Handle successful API response (e.g., parse response data)
                    bool isSuccess = Convert.ToBoolean(result[0]);
                    string successMsg = Convert.ToString(result[1]);
                    //List<string> Result = objUser.DeleteUsers(id);
                    TempData["isSuccess"] = isSuccess;
                    TempData["SuccessMSG"] = successMsg;

                }
                else
                {
                    // Handle failed API call (e.g., log error)
                    TempData["isSuccess"] = false;
                    TempData["SuccessMSG"] = "Error occurred while Deleting user.";
                    return RedirectToPage("./UserIndex");
                }
            }
            else
            {
                return Unauthorized();
            }
            return RedirectToPage("./UserIndex");
        }
    }
}

Pages/UserFolder/EditUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using UsersProject.ApiSevices;
using UsersProject.Middleware;
using UsersProject.Models;

namespace UsersProject.Pages.UserFolder
{
    public class EditUserModel : PageModel
    {
        private readonly WebApis _webApis;
        [BindProperty]
        public UserPerson User { get; set; }

        public SelectList? City { get; set; }

        public EditUserModel(WebApis webApis)
        {
            _webApis = webApis;
        }
        public async Task<ActionResult> OnGet(int? id)
        {
            var isAdmin = TempData["isAdmin"] as bool? ?? false;
            var isUser = TempData["isUser"] as bool? ?? false;
            var userId = Convert.ToInt32(TempData["UserId"] ?? 0);
            TempData.Keep("isAdmin");
            TempData.Keep("isUser");
            TempData.Keep("UserId");

            if (isAdmin || (isUser && userId == id))
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }
                if (Request.Cookies.TryGetValue("jwt_token", out var token))
                {
                    User = await _webApis.GetUserDataApiAsync(id, token: token);
                    TempData["OldUser"] = JsonConvert.SerializeObject(User);
                    City = new SelectList(await _webApis.GetCitiesApiAsync());
                }
                else
                {
                    return Unauthorized();
                }
                //User = await GetUserById(id.Value);

                if (User == null)
                {
                    return NotFound();
                }

                TempData.Keep("UserPassword");

                return Page();
            }
            else
            {
                return RedirectToPage("/Admin");
            }
        }

        public async Task<ActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                    City = new SelectList(await _webApis.GetCitiesApiAsync());
                return Page();
            }

            var oldUser = JsonConvert.DeserializeObject<UserPerson>(TempData["OldUser"] as string);
            var emailChanged = oldUser?.email != User.email;
            var isAdmin = TempData["isAdmin"] as bool? ?? false;

            if (!emailChanged || isAdmin)
            {
                TempData.Keep("isAdmin");
                //var result = objUser.UpdateUsers(User);
                if (Request.Cookies.ContainsKey("jwt_token"))
                {
                    var response = await _webApis.UserUpdateApiAsync(User);

                    if (response.IsSuccessStatusCode)
                    {
                        string responseContent = DecryptionHelper.DecryptString(await response.Content.ReadAsStringAsync());
                        var result = JsonConvert.DeserializeObject<List<string>>(responseContent);
                        var isSuccess = Convert.ToBoolean(result[0]);
                        var successMsg = Convert.ToString(result[1]);
                        if (isSuccess)
                        {
                            TempData["isSuccess"] = isSuccess;
                            TempData["SuccessMSG"] = successMsg;
                        }
                        else
                        {
                            TempData["isSuccess"] = false;
                            TempData["SuccessMSG"] = "";
                        }
                    }
                    else
                    {
                        // Handle failed API call (e.g., log error)
                        TempData["isSuccess"] = false;
                        TempData["SuccessMSG"] = "Error occurred while updating user.";
                        return RedirectToPage("./UserIndex");
                    }
                    var isUser = TempData["isUser"] as bool? ?? false;
                    if (isUser)
                    {
                        TempData.Keep("isUser");
                        return RedirectToPage("./UserDetails", new { id = oldUser?.userID });
                    }

                    return RedirectToPage("./UserIndex");

                }
                else
                {
                    return Unauthorized();
                }
            }
            else
            {
                string otp = await _webApis.SendOtpApiAsync(User.email, User.firstName);
                //var otp = objUser.SendOTPEmail(User.email, User.firstName);
                TempData["OTP"] = otp;
                TempData["User"] = JsonConvert.SerializeObject(User);
                return RedirectToPage("./OtpVerification");
            }
        }
    }
}

Pages/UserFolder/UserDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UsersProject.ApiSevices;
using UsersProject.Models;

namespace UsersProject.Pages.UserFolder
{
    public class UserDetailsModel : PageModel
    {

        private readonly WebApis _webApi;

        public UserPerson User { get; set; }
        public UserDetailsModel(WebApis webApis)
        {
            _webApi = webApis;
        }
        public async Task<IActionResult> OnGet(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            bool isUser = TempData["isUser"] != null && (bool)TempData["isUser"];
            TempData.Keep("isUser");
            string userPassword = TempData["UserPassword"]?.ToString();
            TempData.Keep("UserPassword");

            if (Request.Cookies.TryGetValue("jwt_token", out var token))
            {
                if (isUser && userPassword != null)
                {
                    User = await _webApi.GetUserDataApiAsync(id, userPassword, token);
                    //User = await _objUser.GetUserDataAsync(id.Value, userPassword);
                }
                else
                {
                    User = await _webApi.GetUserDataApiAsync(id, token:token);
                    //User = await _objUser.GetUserDataAsync(id.Value);
                }
            }
            else
            {
                return Unauthorized();
            }


            if (User == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

Pages/UserFolder/forgotPassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using UsersProject.ApiSevices;
using UsersProject.Middleware;

namespace UsersProject.Pages.UserFolder
{
    public class forgotPasswordModel : PageModel
    {
        private readonly WebApis _webApis;

        [BindProperty]
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string userEmail { get; set; }

        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public string confirmPassword { get; set; }

        public forgotPasswordModel(WebApis webApis)
        {
            _webApis = webApis;
        }
        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPostAsync()
        {
            if (userEmail != null)
            {
                //if (objUser.ValidateUserByEmail(userEmail) != 0)
                int UserID = await _webApis.UserVaidationByMailApiAsync(userEmail);
                if (UserID != 0)
                {
                    string otp = await _webApis.SendOtpApiAsync(userEmail, "");
                    //string otp = objUser.SendOTPEmail(userEmail, "");
                    TempData["OTP"] = otp;

                    TempData["UserId"] = UserID;
                    //TempData["UserId"] = objUser.ValidateUserByEmail(userEmail);

                    return RedirectToPage("./OtpVerification", new { isResetPassword = "true" });
                }
                else
                {
                    TempData["isSuccess"] = false;
                    TempData["SuccessMSG"] = "User does not exist!!";
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostResetPasswordAsync()
        {
            if (Password == confirmPassword)
            {
                int UserId = 0;
                if (TempData["UserId"] != null)
                {
                    UserId = Convert.ToInt32(TempData["UserId"]);
                }
                if (UserId != 0)
                {
                    var response = await _webApis.UserUpdateApiAsync(UserId: UserId, Password: Password);
                    if (response.IsSuccessStatusCode)
                    {
                        string responseContent = DecryptionHelper.DecryptString(await response.Content.ReadAsStringAsync());
                        var result = JsonConvert.DeserializeObject<List<string>>(responseContent);

                        var isSuccess = Convert.ToBoolean(result[0]);
                        var successMsg = Convert.ToString(result[1]);

                        TempData["isSuccess"] = isSuccess;
                        TempData["SuccessMSG"] = successMsg;

                        var isUser = TempData["isUser"] as bool? ?? false;
                        TempData.Keep("isUser");

                        if (isSuccess && !isUser)
                        {
                            return RedirectToPage("./UserDetails", new { id = result[2] });
                        }

                        return RedirectToPage("./UserIndex");
                    }
                    else
                    {
                        TempData["isSuccess"] = false;
                        TempData["SuccessMSG"] = "Error occurred while updating user.";
                        return RedirectToPage("./CreateUsers");
                    }
                }
                else
                {
                    TempData["isSuccess"] = false;
                    TempData["SuccessMSG"] = "User does not exist!";
                }
            }
            else
            {
                TempData["isSuccess"] = false;
                TempData["SuccessMSG"] = "Password and confirm password do not match!";
            }
            return Page();
        }
    }
}

Pages/UserFolder/DeleteAll.cshtml
@page
@model UsersProject.Pages.UserFolder.DeleteAllModel
@{
    ViewData["Title"] = "Delete All";
}


@if (TempData["isDeleteAll"] == null || (TempData["isDeleteAll"] != null && TempData["isDeleteAll"] as bool? == false))
{
<form method="post" asp-page-handler="ConfirmAdmin">
    <div class="d-flex flex-column align-items-center justify-content-center gap-2">
        @* <h2>Delete</h2> *@
        <h3>Are you sure you want to delete all the Data? 👹</h3>
        <div class="form-floating text-light mb-2">
            <input type="password" name="password" id="password" autocomplete="off" class="form-control" style="color:#fff;outline:none; background-color:#ffffff10;" placeholder="Password...">
                <button type="button" class="btn text-light togglePassword" style="position:absolute; right:5px; top:18%; outline:none; box-shadow:none; border:none; background:none;">
                    <svg xmlns="http://www.w3.org/2000/svg" height="15" width="16.75" viewBox="0 0 600 512"><path class="eyeIcon" fill="currentColor" d="M288 80c-65.2 0-118.8 29.6-159.9 67.7C89.6 183.5 63 226 49.4 256c13.6 30 40.2 72.5 78.6 108.3C169.2 402.4 222.8 432 288 432s118.8-29.6 159.9-67.7C486.4 328.5 513 286 526.6 256c-13.6-30-40.2-72.5-78.6-108.3C406.8 109.6 353.2 80 288 80zM95.4 112.6C142.5 68.8 207.2 32 288 32s145.5 36.8 192.6 80.6c46.8 43.5 78.1 95.4 93 131.1c3.3 7.9 3.3 16.7 0 24.6c-14.9 35.7-46.2 87.7-93 131.1C433.5 443.2 368.8 480 288 480s-145.5-36.8-192.6-80.6C48.6 356 17.3 304 2.5 268.3c-3.3-7.9-3.3-16.7 0-24.6C17.3 208 48.6 156 95.4 112.6zM288 336c44.2 0 80-35.8 80-80s-35.8-80-80-80c-.7 0-1.3 0-2 0c1.3 5.1 2 10.5 2 16c0 35.3-28.7 64-64 64c-5.5 0-10.9-.7-16-2c0 .7 0 1.3 0 2c0 44.2 35.8 80 80 80zm0-208a128 128 0 1 1 0 256 128 128 0 1 1 0-256z" /></svg>
                </button>
            <label for="SearchFirstName">Password</label>
        </div>
        @* <input type="password" class=" py-1 px-2 border-light border-1 rounded text-light" style="outline:none; background-color:#ffffff20;" id="password" name="lastName" placeholder="Password"> *@
        <button type="submit" class="btn btn-outline-warning">
            Confirm Delete
        </button>
    </div>
</form>
}
@if (TempData["isDeleteAll"] as bool? == true)
{
    <div id="confirm-del" class="d-flex flex-column align-items-center justify-content-center gap-2">
        <h5>You can still cancel the operation 😶 </h5>
        <form method="post" asp-page-handler="DeleteAll">
            <button class="btn btn-outline-danger rounded" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="13.5" viewBox="0 0 512 512"><path fill="currentColor" d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z" /></svg>
                Confirm
            </button>
            <a asp-page="./UserIndex" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
}


@if (TempData["isSuccess"] != null)
{
    @if (Convert.ToBoolean(TempData["isSuccess"]) == false)
    {
        <script>
            toastr.error("@TempData["SuccessMSG"]", "Error");
        </script>
    }
}

Pages/UserFolder/forgotPassword.cshtml
@page
@model UsersProject.Pages.UserFolder.forgotPasswordModel
@{
    ViewData["Title"] = "Forgot password";
}


@if (TempData["ResetPasswordUserValidated"] != null && TempData["ResetPasswordUserValidated"] as Boolean? == true)
{
    TempData.Keep("ResetPasswordUserValidated");
    <div class="h-100 container d-flex justify-content-center">
        <div class="w-50 d-flex justify-content-center">
            <form asp-page-handler="ResetPassword" onsubmit="showLoader()" method="post" class="row gx-0 gy-1 custom-border-div custom-otp-form" style="max-width:350px" id="forgotpassword">
                <h1 class="mt-0 mb-0">Reset Password</h1>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*  <div class="form-custom-group form-group col-sm-12 col-md-12 mt-3">
                    <p>An OTP will be sent to your registered email address</p>
                </div> *@
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-3">
                    <div class="input-group-svg" style="position:relative">
                        <svg style="position:absolute;left:10px;top:33%" xmlns="http://www.w3.org/2000/svg" height="14" width="14" viewBox="0 0 512 512"><path fill="currentColor" d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"></path></svg>
                        <input type="password" id="Password" style="padding: 5px 10px 5px 30px;" class="form-control" asp-for='@Model.Password' value="@Model.Password" aria-describedby="emailHelp" placeholder="Enter Password" required>
                        <button type="button" class="btn text-light togglePassword" style="position:absolute; right:5px; top:0%; outline:none; box-shadow:none; border:none; background:none;">
                            <svg xmlns="http://www.w3.org/2000/svg" height="15" width="16.75" viewBox="0 0 600 512"><path class="eyeIcon" fill="currentColor" d="M288 80c-65.2 0-118.8 29.6-159.9 67.7C89.6 183.5 63 226 49.4 256c13.6 30 40.2 72.5 78.6 108.3C169.2 402.4 222.8 432 288 432s118.8-29.6 159.9-67.7C486.4 328.5 513 286 526.6 256c-13.6-30-40.2-72.5-78.6-108.3C406.8 109.6 353.2 80 288 80zM95.4 112.6C142.5 68.8 207.2 32 288 32s145.5 36.8 192.6 80.6c46.8 43.5 78.1 95.4 93 131.1c3.3 7.9 3.3 16.7 0 24.6c-14.9 35.7-46.2 87.7-93 131.1C433.5 443.2 368.8 480 288 480s-145.5-36.8-192.6-80.6C48.6 356 17.3 304 2.5 268.3c-3.3-7.9-3.3-16.7 0-24.6C17.3 208 48.6 156 95.4 112.6zM288 336c44.2 0 80-35.8 80-80s-35.8-80-80-80c-.7 0-1.3 0-2 0c1.3 5.1 2 10.5 2 16c0 35.3-28.7 64-64 64c-5.5 0-10.9-.7-16-2c0 .7 0 1.3 0 2c0 44.2 35.8 80 80 80zm0-208a128 128 0 1 1 0 256 128 128 0 1 1 0-256z" /></svg>
                        </button>
                    </div>
                    <span asp-validation-for="@Model.Password" class="text-danger"></span>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-3">
                    <div class="input-group-svg" style="position:relative">
                        <svg style="position:absolute;left:10px;top:33%" xmlns="http://www.w3.org/2000/svg" height="14" width="12.25" viewBox="0 0 448 512"><path fill="currentColor" d="M144 144v48H304V144c0-44.2-35.8-80-80-80s-80 35.8-80 80zM80 192V144C80 64.5 144.5 0 224 0s144 64.5 144 144v48h16c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V256c0-35.3 28.7-64 64-64H80z"></path></svg>
                        <input type="password" id="confirmPassword" style="padding: 5px 10px 5px 30px;" class="form-control" asp-for='@Model.confirmPassword' value="@Model.confirmPassword" aria-describedby="emailHelp" placeholder="Confirm Password" required>
                        <button type="button" class="btn text-light togglePassword" style="position:absolute; right:5px; top:0%; outline:none; box-shadow:none; border:none; background:none;">
                            <svg xmlns="http://www.w3.org/2000/svg" height="15" width="16.75" viewBox="0 0 600 512"><path class="eyeIcon" fill="currentColor" d="M288 80c-65.2 0-118.8 29.6-159.9 67.7C89.6 183.5 63 226 49.4 256c13.6 30 40.2 72.5 78.6 108.3C169.2 402.4 222.8 432 288 432s118.8-29.6 159.9-67.7C486.4 328.5 513 286 526.6 256c-13.6-30-40.2-72.5-78.6-108.3C406.8 109.6 353.2 80 288 80zM95.4 112.6C142.5 68.8 207.2 32 288 32s145.5 36.8 192.6 80.6c46.8 43.5 78.1 95.4 93 131.1c3.3 7.9 3.3 16.7 0 24.6c-14.9 35.7-46.2 87.7-93 131.1C433.5 443.2 368.8 480 288 480s-145.5-36.8-192.6-80.6C48.6 356 17.3 304 2.5 268.3c-3.3-7.9-3.3-16.7 0-24.6C17.3 208 48.6 156 95.4 112.6zM288 336c44.2 0 80-35.8 80-80s-35.8-80-80-80c-.7 0-1.3 0-2 0c1.3 5.1 2 10.5 2 16c0 35.3-28.7 64-64 64c-5.5 0-10.9-.7-16-2c0 .7 0 1.3 0 2c0 44.2 35.8 80 80 80zm0-208a128 128 0 1 1 0 256 128 128 0 1 1 0-256z" /></svg>
                        </button>
                    </div>
                    <span asp-validation-for="@Model.confirmPassword" class="text-danger"></span>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-2">
                    <button type="submit" class="verifyButton">Save</button>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-2">
                    <a asp-page="/Index" class="btn btn-outline-light w-100">Go Back</a>
                    @* <input type="hidden" name="Action" value="Verify" id="actionInput" /> *@
                </div>

            </form>
        </div>
    </div>
}
else if(TempData["ResetPasswordUserValidated"] == null || TempData["ResetPasswordUserValidated"] as Boolean? != true)
{
    TempData.Keep("ResetPasswordUserValidated");
    <div class="h-100 container d-flex justify-content-center">
        <div class="w-50 d-flex justify-content-center">
            <form method="post" onsubmit="showLoader()" class="row gx-0 gy-1 custom-border-div custom-otp-form" style="max-width:350px" id="forgotpassword">
                <h1 class="mt-0 mb-0">Forgot Password</h1>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-3">
                    <p>An OTP will be sent to your registered email address</p>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-3">
                    <div class="input-group-svg" style="position:relative">
                        <svg style="position:absolute;left:10px;top:33%" xmlns="http://www.w3.org/2000/svg" height="15" width="15" viewBox="0 0 512 512"><path fill="currentColor" d="M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z" /></svg>
                        <input type="email" id="email" style="padding: 5px 10px 5px 30px;" class="form-control" asp-for='@Model.userEmail' value="@Model.userEmail" aria-describedby="emailHelp" placeholder="Enter a valid Email" required>
                    </div>
                    <span asp-validation-for="@Model.userEmail" class="text-danger"></span>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-2">
                    <button type="submit" class="verifyButton">Send OTP</button>
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12 mt-2">
                    <a asp-page="/Index" class="btn btn-outline-light w-100">Go Back</a>
                    @* <input type="hidden" name="Action" value="Verify" id="actionInput" /> *@
                </div>
                <div class="form-custom-group form-group col-sm-12 col-md-12">
                    <p class="mt-3 mb-0">
                        Don't have an account?
                        <a asp-page="./createUsers" class="" style="box-shadow:none;outline:none;text-decoration:none;">Sign up</a>
                    </p>
                    <span id="countdownTimer" style=""></span>
                </div>
            </form>
        </div>
    </div>
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

@if (TempData["isSuccess"] != null)
{
    @if (Convert.ToBoolean(TempData["isSuccess"]) == false)
    {
        <script>
            toastr.error("@TempData["SuccessMSG"]", "Error");
        </script>
    }
}